// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// Update provides a mock function with given fields: msg
func (_m *Observer) Update(msg string) {
	_m.Called(msg)
}
