HealthzBindAddress: "0.0.0.0:12345"
MetricsBindAddress: "0.0.0.0:12346"
  Telemetry:
    Name: jaeger
    ResourceAttributes:
      - Key: env
        Value: example
    EndPoint: "0.0.0.0:55300"
#    EndPoint: http://localhost:14268/api/traces
#    Jaeger:
#      Password: passwd
#      UserName: admin